version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.4
  jmatsu:
    executors:
      default-executor:
        docker:
          - image: circleci/golang:1.17
        working_directory: /go/src/github.com/jmatsu/terraform-provider-slack
        environment:
          - GO111MODULE=on
    commands:
      go-module:
        steps:
          - restore_cache:
              name: Restore go modules cache
              keys:
                - v1-mod-{{ arch }}-{{ checksum "go.mod" }}
          - run: go mod download
          - save_cache:
              name: Save go modules cache
              key: v1-mod-{{ arch }}-{{ checksum "go.mod" }}
              paths:
                - ~/go/pkg/mod/cache
      extend_path:
        steps:
          - run: echo "export PATH=$PWD/bin:$PATH" >> "$BASH_ENV"
    jobs:
      go-build:
        executor: default-executor
        steps:
          - checkout
          - extend_path
          - go-module
          - run: go build .
          - run: go test -v ./...
      go-fmt:
        executor: default-executor
        steps:
          - checkout
          - extend_path
          - go-module
          - run: exec_gofmt
          - run: |
              [[ -n $(git diff) ]] && exit 1 || true

filters:
  only_master: &only_master
    filters:
      branches:
        only: /master/
  ignore_master: &ignore_master
    filters:
      branches:
        ignore: /master/

workflows:
  build:
    jobs:
      - jmatsu/go-build
      - jmatsu/go-fmt
